name: Build oscnews
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Look Changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'


      - run: npm install --unsafe-perm
      - run: npm run build